# Generated by Django 4.2 on 2023-04-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.CharField(blank=True, choices=[('profile-pictures/red.png', 'Red'), ('profile-pictures/blue.png', 'Blue'), ('profile-pictures/yellow.png', 'Yellow')], max_length=100, null=True),
        ),
    ]
