# Generated by Django 4.2 on 2023-05-02 13:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buddies',
            unique_together={('user', 'name')},
        ),
    ]
